import os

env = Environment(
    ENV = os.environ,
    CCFLAGS = '-g -Wall -DUSE_DEBUG',
    CPPPATH=['include','../../src/include','../../src/internal','../../build/proto'],
    LIBPATH=['../../build']
    )
env.ParseConfig("pkg-config --libs libevent libprotobuf-c protobuf")
env.ParseConfig("pkg-config --cflags libevent libprotobuf-c protobuf")
files = ['registry.c','test_binary.c','test_config.c']

riak_c_cunit = env.Program('riak_c_cunit', files, LIBS=['riak_c_client', 'event_core', 'event_extra', 'pthread', 'protobuf', 'protobuf-c','cunit'])
Depends(riak_c_cunit, '../../build/libriak_c_client.a')

conf = Configure(env)
if not conf.CheckLib('pthread'):
  print 'Did not find pthread lib, exiting!'
  Exit(1)

if not conf.CheckLib('protobuf'):
  print 'Did not find protobuf lib, exiting!'
  Exit(1)

if not conf.CheckLib('protobuf-c'):
  print 'Did not find protobuf-c lib, exiting!'
  Exit(1)

if not conf.CheckLib('libevent'):
  print 'Did not find libevent, exiting!'
  Exit(1)

if not conf.CheckLib('cunit'):
  print 'Did not find cunit, exiting!'
  Exit(1)

#if not conf.CheckLib('riak_c_client'):
#  print 'Did not find riak_c_client, exiting!'
#  Exit(1)

env = conf.Finish()

