import os

env = Environment(
    ENV = os.environ,
    CCFLAGS = '-g -Wall -DUSE_DEBUG',
    CPPPATH=['include','../../src/include','../../src/internal','../../build/proto'],
    LIBPATH=['../../build']
    )
env.ParseConfig("pkg-config --libs libevent_pthreads libevent libprotobuf-c protobuf zlog")
env.ParseConfig("pkg-config --cflags libevent_pthreads libevent libprotobuf-c protobuf zlog")
files = ['example.c', 'riak_command.c']

example = env.Program('riakc_example', files, LIBS=['riak_c_client', 'event_core', 'event_extra', 'libevent_pthreads', 'zlog', 'pthread', 'protobuf', 'protobuf-c','cunit'])
Command("./build/zlog.conf", "zlog.conf", Copy("$TARGET", "$SOURCE"))

conf = Configure(env)
if not conf.CheckLib('pthread'):
  print 'Did not find pthread lib, exiting!'
  Exit(1)

if not conf.CheckLib('protobuf'):
  print 'Did not find protobuf lib, exiting!'
  Exit(1)

if not conf.CheckLib('protobuf-c'):
  print 'Did not find protobuf-c lib, exiting!'
  Exit(1)

if not conf.CheckLib('libevent'):
  print 'Did not find libevent, exiting!'
  Exit(1)

if not conf.CheckLib('zlog'):
  print 'Did not find zlog, exiting!'
  Exit(1)

if not conf.CheckLib('cunit'):
  print 'Did not find cunit, exiting!'
  Exit(1)

#if not conf.CheckLib('riak_c_client'):
#  print 'Did not find riak_c_client, exiting!'
#  Exit(1)

env = conf.Finish()

